-- HRM NKUVO — seed de reclutadoras (regenerado 8 jul 2026 desde directorio_reclutadoras_hrm.xlsx)
-- 84 registros únicos (117 filas originales - 2 institucionales - 31 duplicados entre hojas)
--
-- 12 jul 2026: + padrón oficial STPS (Directorio_Agencias_CON_SitioWeb.xlsx, 79 filas).
-- Depurado a 63 registros nuevos tras cruzar contra los 84 de arriba:
--   - 4 eliminadas por duplicar número de registro STPS dentro del propio archivo
--     (mismo folio con "Tipo de Registro" distinto: Nacional / Empleo en el exterior).
--   - 8 eliminadas por compartir dominio de sitio web con otra fila del mismo archivo
--     (múltiples razones sociales de una misma marca: Prowork x4, Leader People x3, Soraa x2).
--   - 3 eliminadas por ya existir en el directorio de arriba con la misma marca
--     (Adecco, Manpower, Soraa por dominio exacto; Randstad, Serpac, People Care por marca).
-- Total: 84 + 63 = 147 reclutadoras. "Lucrativa: No" (universidades, cámaras empresariales)
-- se incluyó igual, sin excluir, a pedido explícito del usuario.

alter table hrm_recruiters add column if not exists estado text default 'activo';

insert into hrm_recruiters (nombre, industria, sitio_web, email, telefono, ciudad, fuente, estado)
values
  ('Evolucione Querétaro', 'Generalista RH, Querétaro', null, 'reclutamientoqueretaro@evolucione.net', '442 543 8975', 'Santiago de Querétaro, Qro.', 'curado', 'activo'),
  ('Operativo Evenplan', 'Generalista RH, Querétaro', 'https://www.evenplan.com.mx/', null, '442 224 0662', 'Santiago de Querétaro, Qro.', 'curado', 'activo'),
  ('Out Helping Corporativo', 'Generalista RH, Querétaro (oficina corporativa)', 'https://outhelping.mx', null, '442 215 9799', 'Santiago de Querétaro, Qro.', 'curado', 'activo'),
  ('Adecco Querétaro', 'Generalista, outsourcing/temporal, multinacional', 'https://www.adecco.com.mx/', 'calidadmx@adecco.com', '442 242 4425', 'Santiago de Querétaro, Qro. (San Ángel)', 'curado', 'activo'),
  ('Manpower Querétaro', 'Generalista, outsourcing/temporal, multinacional', 'https://www.manpower.com.mx/', null, '01 800 451 1400', 'Santiago de Querétaro, Qro. (Centro)', 'curado', 'activo'),
  ('Centro CIEE', 'Generalista RH, Querétaro', null, 'reclutamiento@centrociee.com.mx', '442 421 8046', 'Santiago de Querétaro, Qro. (Cimatario)', 'curado', 'activo'),
  ('Insourcing Professional Services', 'Generalista RH, Querétaro', null, 'aux.reclutamiento@ipsco.com.mx', '442 242 6463', 'Santiago de Querétaro, Qro. (Carretas)', 'curado', 'activo'),
  ('LMA Services', 'Generalista RH, Querétaro', 'https://lmaservices.com', null, '442 196 6110', 'Santiago de Querétaro, Qro. (Lomas de Casa Blanca)', 'curado', 'activo'),
  ('Worken', 'Generalista RH, Querétaro', 'https://www.workenqueretaro.com', null, '442 248 4952', 'Santiago de Querétaro, Qro. (se cambió de lugar, dirección no confirmada)', 'curado', 'verificar'),
  ('Brainware Assistance & Engineering', 'RH especializado en ingeniería', 'https://www.brainware.com.mx', 'fernandonavarrete@brainware.com.mx', '442 212 4225', 'Santiago de Querétaro, Qro. (Alamos 2da Secc)', 'curado', 'activo'),
  ('OIRH', 'Generalista RH, Querétaro', 'https://oirh.mx', 'marisol.flores@oirh.mx', '2950606', 'Santiago de Querétaro, Qro. (Milenio 3ra Secc)', 'curado', 'activo'),
  ('Randstad Querétaro', 'Generalista, outsourcing/temporal, multinacional', 'https://www.randstad.mx/', null, '442 215 7665', 'Santiago de Querétaro, Qro. (El Marqués/Piamonte)', 'curado', 'activo'),
  ('CICESO Centro Integral de Evaluación', 'Evaluación psicométrica/assessment', 'https://ciceso.mx', 'lacayo@ciceso.com', '442 215 9618', 'Santiago de Querétaro, Qro. (Jardines de la Hacienda)', 'curado', 'activo'),
  ('Serpac Consulting', 'Generalista RH, Querétaro', 'https://www.serpac.mx', 'serpac@serpac.net.mx', '442 242 3931', 'Santiago de Querétaro, Qro. (Mansiones del Valle)', 'curado', 'activo'),
  ('Out Helping (sucursal FINSA - Parque Industrial Querétaro)', 'Generalista RH, Querétaro', 'https://www.aet.mx', null, '442 215 9799', 'El Marqués, Qro. (Parque Industrial FINSA)', 'curado', 'activo'),
  ('People Care', 'Generalista RH, Querétaro', 'https://www.peoplecare.mx', 'eric.malo@peoplecare.com.mx', '442 213 8155', 'Santiago de Querétaro, Qro. (El Jacal)', 'curado', 'activo'),
  ('Lumi Sourcing', 'Generalista RH, Querétaro', 'https://www.lumipeople.com', 'nancyperez@lumipeople.com', '442 215 7695', 'Santiago de Querétaro, Qro. (Los Sauces)', 'curado', 'activo'),
  ('Soraa Consultores', 'Generalista RH, Querétaro', 'https://www.soraaconsultores.com', 'sofia.gonzales@soraaconsultores.com', '442 212 7171', 'Santiago de Querétaro, Qro. (Alamos 3ra Secc)', 'curado', 'activo'),
  ('TASI Soluciones en Capital Humano e IT', 'RH especializado en IT', 'https://www.tasisoluciones.com', 'octavio_ramirez@tasisoluciones.com', '442 388 1022', 'Santiago de Querétaro, Qro. (La Piedad)', 'curado', 'activo'),
  ('Sercah Consultores', 'Generalista RH, Querétaro', 'https://www.sercah.com.mx', null, null, 'Santiago de Querétaro, Qro. (Residencial Italia, C.E.A.)', 'curado', 'verificar'),
  ('Recruitment & Human Solutions (RHS)', 'Generalista RH, Querétaro', 'https://www.rhs.com.mx/', 'paola.camarena@rhs.com.mx', '442 391 7888 / 442 561 7391', 'El Pueblito, Qro.', 'curado', 'activo'),
  ('Out Helping (Centro de Reclutamiento, Parque Industrial Querétaro)', 'Generalista RH, Querétaro', 'https://outhelping.mx', null, '01 461 616 2712', 'Santiago de Querétaro, Qro. (Parque Industrial Querétaro)', 'curado', 'activo'),
  ('Narus Bolsa de Empleo', 'Bolsa de empleo/generalista, Querétaro', null, 'daniel.hernandez@narus.com.mx', '442 383 1424', 'Santiago de Querétaro, Qro. (Carretas)', 'curado', 'activo'),
  ('Team Solution México', 'Generalista RH, Querétaro', null, 'jmelo@teamrh.mx', '442 213 5323', 'Santiago de Querétaro, Qro. (Carretas)', 'curado', 'activo'),
  ('Out Helping (sucursal FINSA, El Marqués)', 'Generalista RH, Querétaro', 'https://outhelping.mx', null, '442 221 6500', 'El Marqués, Qro. (Parque Industrial FINSA)', 'curado', 'activo'),
  ('Out Helping (sucursal Marqués)', 'Generalista RH, Querétaro', 'https://outhelping.mx', null, '442 253 1123', 'El Marqués, Qro. (Parque Industrial El Marqués)', 'curado', 'activo'),
  ('Personae Consultores', 'Generalista RH, Querétaro', 'https://personaeconsultores.com', null, '442 161 2775', 'Santiago de Querétaro, Qro. (Fracc. Claustro del Sur)', 'curado', 'verificar'),
  ('Amrop / Seelinger y Conde', 'Multinacional, executive search C-level', 'https://www.amrop.com/mx/es/', null, '+52 81 2557 0417', 'Monterrey / CDMX', 'curado', 'activo'),
  ('ADECCO Nápoles', 'Generalista, outsourcing/temporal, multinacional', 'https://www.adecco.com.mx/', 'calidadmx@adecco.com', '800 832 9050 / 55 5062 5000', 'CDMX (Nápoles)', 'curado', 'activo'),
  ('AIRH Consultores', 'Generalista RH: reclutamiento, nómina, consultoría', 'https://www.airh.mx/', 'malmazan@airh.com.mx', '55 6017 7670', 'CDMX (Del Valle)', 'curado', 'activo'),
  ('Al Smith y Asociados', 'Ejecutivo/boutique, investigación directa', 'http://alsmith.com.mx/', 'alsmith@alsmith.com.mx', null, 'Querétaro', 'curado', 'activo'),
  ('Alpe Consultores', 'Consultoría gerencial/capacitación', 'http://www.alpeconsultores.com.mx/', null, '55 5524 1720 / 55 5362 9147', 'CDMX (Del Valle)', 'curado', 'verificar'),
  ('Antal International', 'Multinacional generalista (IT/ingeniería/ventas)', 'https://www.antal.com/recruitment/mexico-p', null, null, 'CDMX (Polanco)', 'curado', 'activo'),
  ('APOYO CONFIABLE DE PERSONAL', 'Generalista ejecutivo/operativo', 'https://www.apoyoconfiabledepersonal.com.mx/', 'apoyoconfiable@prodigy.net.mx', '55 5744 4500', 'CDMX (Roma Norte)', 'curado', 'activo'),
  ('ARGÜELLES CAPITAL EJECUTIVO', 'Boutique ejecutivo, +30 años', 'https://www.capitalejecutivo.com.mx/', 'arguelles@capitalejecutivo.com.mx', '55 1085 7233 / 55 5662 3858', 'CDMX (Santa Fe)', 'curado', 'activo'),
  ('ARMSTRONG', 'Evaluación psicométrica / plataforma tecnológica', 'https://www.armstrong.com.mx/', 'comunidad@armstrong.com.mx', '55 5212 1020', 'CDMX', 'curado', 'activo'),
  ('ASIRH', 'Generalista RH, outsourcing/nómina', 'http://www.asirh.com.mx/', 'direccion.general@asirh.com.mx', '+52 222 248 0959', 'Puebla', 'curado', 'activo'),
  ('AVANTGARDE (AGHCC)', 'Executive search + team building + assessment', 'https://www.aghcc.com/', 'contacto@aghcc.com', '+52 55 3640 0552', 'CDMX / Monterrey / Querétaro', 'curado', 'activo'),
  ('AXIS CONSULTORES', 'Generalista RH: headhunting + nómina', 'https://axisconsultores.com/', 'ventas@axisconsultores.com', '55 5559 3833 / 3839', 'CDMX (Del Valle)', 'curado', 'activo'),
  ('Aymerich Business & Consulting', 'Boutique especializado Telecom/IT/Ingeniería', 'https://aymerichbc.com/', 'corporativo@aymerichbc.com', '55 5017 5662 / 55 2628 0627', 'Edo. México (Tlalnepantla/Ecatepec)', 'curado', 'activo'),
  ('BARREDA CONSULTORES', 'Boutique ejecutivo alto/medio, red internacional', 'https://barredaygonzalez.com/', null, null, 'CDMX (Del Valle)', 'curado', 'activo'),
  ('BE EXECUTIVE', 'Reclutamiento ejecutivo + estudios socioeconómicos', 'http://www.beexecutive.com/', null, null, 'CDMX (sin confirmar)', 'curado', 'verificar'),
  ('BEST RECURSOS HUMANOS', 'Generalista + outsourcing/nómina, 25+ años', 'https://bestrecursoshumanos.com', 'reclutamiento@bestrecursoshumanos.com', '+52 55 5661 3336', 'CDMX (Guadalupe Inn)', 'curado', 'activo'),
  ('BLEUMIND', 'Boutique ejecutivo + career transition', 'https://bleumind.com', 'contacto@bleumind.com', 'no publicado (WhatsApp/LinkedIn)', 'San Pedro Garza García, N.L.', 'curado', 'activo'),
  ('Boege & Business', 'Boutique germano-mexicana, RH para empresas europeas', 'https://boege-b.com.mx', 'info@boege-b.com.mx', '+52 55 5953 3083', 'CDMX (Santa Fe)', 'curado', 'activo'),
  ('Boyden Mexico', 'Multinacional, ejecutivo/C-level y board', 'https://boyden.com/mexico/', 'mexico@boyden.com', '+52 55 3145 9263', 'CDMX (Santa Fe)', 'curado', 'activo'),
  ('C&H Empresarial', 'Outsourcing/suministro de personal', 'https://cyhempresarial.com', 'gerente.celaya@cyhempresarial.com.mx', '461 159 5576', 'Celaya, Guanajuato', 'curado', 'verificar'),
  ('CASE CONSULTORES', 'Generalista, búsqueda y selección de talento', 'https://caseconsultores.com.mx', null, '+52 55 5663 2400', 'CDMX (Insurgentes)', 'curado', 'activo'),
  ('CATENON', 'Multinacional tech-driven executive search', 'https://catenon.com', null, null, 'Internacional (HQ Madrid)', 'curado', 'activo'),
  ('CLAUDIO BENITEZ CONSULTORES', 'Selección de directivos y gerentes', 'http://www.claudiobenitezheadhunter.com/', null, '222 357 0534', 'Puebla / Edo. México (fuentes distintas)', 'curado', 'verificar'),
  ('COCA CONSULTORES', 'Generalista RH + fiscal/contable, 25+ años', 'https://cocaconsultores.com', 'contacto@cocaconsultores.com', '(55) 2454 2174 / 2175', 'CDMX (Álvaro Obregón)', 'curado', 'activo'),
  ('Confisa Group', 'Boutique internacional retained executive search', 'https://confisagroup.com', 'info@confisagroup.com', '+52 55 1660 8135', 'CDMX (Polanco)', 'curado', 'activo'),
  ('Consystar Consultores', 'Generalista: RH, reclutamiento, head hunting', 'https://consystar.mx', 'marta.rodriguez@consystar.com', '55 5611 4553 / 6910', 'CDMX (Álvaro Obregón)', 'curado', 'activo'),
  ('COSMIC', 'Outsourcing/staffing de alto volumen', 'https://cosmic.com.mx', 'info@grupocosmic.com', '800 288 9353', 'CDMX (Benito Juárez)', 'curado', 'activo'),
  ('CREO SERVICES', 'Ejecutivo/generalista, 12+ años', 'https://creoservices.com', 'direccion@creoservices.com', '+52 81 8335 0492', 'Monterrey / San Pedro Garza García', 'curado', 'activo'),
  ('Cuadrivium', 'Outsourcing/administración de RH, desde 1999', 'https://cuadrivium.com', null, null, 'CDMX (Guadalupe Inn)', 'curado', 'activo'),
  ('DEZA SEARCH', 'Boutique ejecutivo multinacional, desde 1990', 'https://dezasearch.com', 'contacto@dezasearch.com', '+52 55 5241 5221', 'CDMX (Río Lerma)', 'curado', 'activo'),
  ('DHR Global (antes DHR International)', 'Multinacional top-5 global retained search, C-level', 'https://dhrglobal.com', null, '+52 55 5281 4849', 'CDMX (Reforma)', 'curado', 'activo'),
  ('DIRECCION HUMANA', 'Generalista: reclutamiento, estudios socioeconómicos', 'https://direccionhumana.com', 'info@direccionhumana.com', '(55) 2848 6393 / 2724 1970', 'CDMX (Polanco)', 'curado', 'activo'),
  ('Dúo Sinergia', 'Outsourcing/nómina + generalista, multi-sucursal', 'https://duosinergia.com', 'hermosillo@duosinergia.com', '(55) 5543 0205', 'CDMX / Guadalajara / Hermosillo', 'curado', 'activo'),
  ('E People Consulting', 'RH generalista (reclutamiento, capacitación, coaching)', 'https://epeopleconsulting.com', 'clientes@epeopleconsulting.org', null, 'San Pedro Garza García, N.L.', 'curado', 'activo'),
  ('EGON ZEHNDER INTERNACIONAL', 'Multinacional boutique, executive/board search C-level', 'https://www.egonzehnder.com', null, '55 5540 7635', 'CDMX (Lomas de Chapultepec)', 'curado', 'activo'),
  ('Ejecutivos Seleccionados (GES)', 'Generalista Head Hunting + planta + payrolling, desde 1971', 'https://www.grupoejecutivos.com', null, '55 5523 5731', 'CDMX (Del Valle)', 'curado', 'activo'),
  ('EliteBrain.com', 'Multinacional boutique, C-level + coaching (Grupo Confisa Intl.)', 'https://elitebrain.com', 'info@elitebrain.com', null, 'CDMX (Polanco) / Monterrey', 'curado', 'activo'),
  ('EULEN', 'Multinacional outsourcing/facility services', 'https://www.eulen.com.mx', null, '(55) 5002 7000', 'CDMX (Del Valle)', 'curado', 'activo'),
  ('EXCELENCIA', 'RH generalista, reclutamiento y selección', 'https://excelencia.com.mx', null, '(55) 9418 7236', 'CDMX (Polanco)', 'curado', 'activo'),
  ('Global Recruiters', 'Boutique internacional, manufactura/hospitalidad', 'https://global-recruiters.com', 'info@global-recruiters.com', '+52 664 881 0378 (WhatsApp)', 'Tijuana, Baja California', 'curado', 'activo'),
  ('Great Team Empresarial', 'RH generalista para PyMEs', 'https://greatteam.mx', 'ventas@greatteam.com.mx', '55 2489 0216 / 0217', 'CDMX (Roma Norte)', 'curado', 'activo'),
  ('Grupo Argos / StarChoice', 'Headhunting supervisión/gerencial/directivo, foco turismo', 'https://www.starchoice.com.mx', 'info@starchoice.com.mx', '998 241 4622', 'Cancún, Quintana Roo', 'curado', 'activo'),
  ('Grupo DCH', 'Reclutamiento ejecutivo/operativo/masivo + REPSE', 'https://dchkw.com.mx', 'contacto@dchkw.com.mx', '55 5393 1490 / 55 6350 9982', 'Naucalpan, Edo. México', 'curado', 'activo'),
  ('Korn Ferry México', 'Multinacional, executive search + consultoría organizacional', 'https://www.kornferry.com/', null, '55 5095 9500', 'CDMX (Lomas de Chapultepec) / Monterrey', 'curado', 'activo'),
  ('Michael Page / PageGroup México', 'Multinacional, selección especializada y ejecutiva', 'https://www.michaelpage.com.mx/', null, null, 'CDMX (Reforma) / Monterrey / Guadalajara', 'curado', 'activo'),
  ('T-mapp', 'Reclutamiento tech-enabled con IA', 'https://t-mapp.com/', null, null, 'Origen Colombia, opera en México sin oficina confirmada', 'curado', 'verificar'),
  ('Hireline', 'Reclutamiento de talento tecnológico (TI) con IA', 'https://hireline.io/', 'contacto@hireline.io', null, 'Querétaro', 'curado', 'verificar'),
  ('Lupa Hire', 'Staffing/EOR/RPO remoto, roles tech y senior', 'https://lupahire.com/', 'talent@lupahire.com', null, 'Remoto LatAm (México, Colombia, Argentina, Brasil)', 'curado', 'verificar'),
  ('Top Hire', 'Executive search para multinacionales y Fortune 500', 'https://top-hire.com/', null, null, 'México (sin confirmar)', 'curado', 'verificar'),
  ('People Connect / People Connection', 'RH integral: reclutamiento, nómina, psicometrías', 'https://peopleconnect.com.mx/', 'recursoshumanos@peopleconnect.com.mx', '(55) 6820 3100 CDMX / (222) 934 5100 Puebla', 'CDMX / Puebla / Toluca', 'curado', 'verificar'),
  ('ALGI Consultores', 'Reclutamiento consultivo, psicometrías, capacitación, RH integral', 'https://algi.mx/', 'hola@algi.mx', '+52 55 7100 0200 / 55 6297 1084', 'CDMX / Puebla / Querétaro / Tlaxcala / Morelos', 'curado', 'activo');
insert into hrm_recruiters (nombre, industria, sitio_web, email, telefono, ciudad, fuente, estado)
values
  ('Universidad Autónoma de Aguascalientes', 'Institución / cámara empresarial — bolsa de empleo registrada ante STPS', 'https://www.uaa.mx', null, '449 918 0431', 'Aguascalientes, Ags.', 'curado', 'activo'),
  ('Universidad Tecnológica de Aguascalientes', 'Institución / cámara empresarial — bolsa de empleo registrada ante STPS', 'https://www.utags.edu.mx', null, '449 910 5000 EXT. 124', 'Aguascalientes, Ags.', 'curado', 'activo'),
  ('Tu Empleo Ideal S. C.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.facebook.com/tuempleoidealmx/', null, '68 6304 7105; 68 6945 2653', 'Mexicali, B. C.', 'curado', 'activo'),
  ('Centro Empresarial Coahuila Sureste S. P.', 'Institución / cámara empresarial — bolsa de empleo registrada ante STPS', 'https://coparmexcoahuila.org.mx', null, '844 415 8941; 844 415 3412; 844 415 8618; 844 416 2307; 844 416 2310', 'Coahuila', 'curado', 'activo'),
  ('Human Staff S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.humanstaff.com', null, '871 747 03 00', 'Torreón, Coah.', 'curado', 'activo'),
  ('Zesati Internacional S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://zesatiinternacional.com', null, '871 688 1272', 'Torreón, Coah.', 'curado', 'activo'),
  ('Best Staff Services S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://beststaff.mx', null, '87 1776 3318', 'Torreón, Coah.', 'curado', 'activo'),
  ('Bussines Management Service S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://bmghumancapital.mx', null, '87 1187 5502', 'Torreón, Coah.', 'curado', 'verificar'),
  ('Ech Servicios Integrales S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://ech.com.mx', null, '87 1724 0620', 'Torreón, Coah.', 'curado', 'activo'),
  ('Fabiola Berenice Constantino Solís (Buró Laboral)', 'Agencia de colocación privada — registrada ante STPS', 'http://www.burolaboral.mx', null, '961 613 6987; 961 614 7851', 'Tuxtla Gutierrez, Chis.', 'curado', 'activo'),
  ('Regina Vega Macías (Vega Consulting)', 'Agencia de colocación privada — registrada ante STPS', 'https://www.vegaconsulting.com.mx', null, '961 336 1626', 'Tuxtla Gutierrez, Chis.', 'curado', 'activo'),
  ('Triunfo Activo S. A. de C. V. (Chc Empresarial)', 'Agencia de colocación privada — registrada ante STPS', 'https://chcempresarial.com', null, '96 1207 3059', 'Tuxtla Gutierrez, Chis.', 'curado', 'activo'),
  ('Centro Empresarial de Chihuahua S. P.', 'Institución / cámara empresarial — bolsa de empleo registrada ante STPS', 'https://www.coparmexchihuahua.org', null, '614 416 5228 EXT. 3', 'Chihuahua, Chih.', 'curado', 'activo'),
  ('Human Select, S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.humanselect.com.mx', null, '55 5264 8319; 55 3547 9075', 'Ciudad de México, CDMX', 'curado', 'activo'),
  ('Cierto México S. C.', 'Institución / cámara empresarial — bolsa de empleo registrada ante STPS', 'https://ciertoglobal.org', null, '55 4774 4880', 'Alcaldía Benito Juárez, Ciudad de México', 'curado', 'activo'),
  ('ILUM Asesores S. de R. L. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.ilumasesores.com', null, '55 28 50 71 10', 'Ciudad de México, CDMX', 'curado', 'activo'),
  ('Staffing Personal S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.staffingpersonal.com', null, '55 5687 3617', 'Alcaldía Benito Juárez, Ciudad de México', 'curado', 'activo'),
  ('3R Respuesta Rápida en Reclutamiento S. A. P. I. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://reclutamiento3r.com', null, '55 2772 5211', 'Ciudad de México, CDMX', 'curado', 'activo'),
  ('Asociación Mexicana de Empresas de Capacitación y Administración de Recursos Humanos A. C.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.amech.mx', null, '55 9039 7317', 'Ciudad de México, CDMX', 'curado', 'activo'),
  ('Organizacion y Estrategia Humana S. de R. L. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://estrategiahumana.com', null, '55 5207 4223', 'Ciudad de México, CDMX', 'curado', 'activo'),
  ('Vanzar Link S. A de C. V. (Working Link)', 'Agencia de colocación privada — registrada ante STPS', 'https://workinglink.mx', null, '55 6719 1119', 'Ciudad de México, CDMX', 'curado', 'activo'),
  ('Fundación Pradillo A. C.', 'Institución / cámara empresarial — bolsa de empleo registrada ante STPS', 'https://fundacionpradillo.org', null, '55 9039 7317 Ext. 1001', 'Ciudad de México, CDMX', 'curado', 'activo'),
  ('Human Capital Assets Corporate S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'http://hcapitalassets.com', null, '55 5922 7929', 'Alcaldía Cuauhtémoc, Ciudad de México', 'curado', 'activo'),
  ('Prowork Energy S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.prowork.mx', null, '22 2708 0136', 'Ciudad de México, CDMX', 'curado', 'activo'),
  ('Bacher Zoppi, S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.bacherzoppi.com.mx', null, '55 9421 8040', 'Ciudad de México', 'curado', 'activo'),
  ('Global Workers Management S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.globalworkers.com.mx', null, '77 1143 0045', 'Tepehuacán de Guerrero, Hidalgo', 'curado', 'activo'),
  ('Grupo Empresarial Cosea S. C.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.cosea.mx', null, '33 3133 5346', 'Zapopan, Jal.', 'curado', 'activo'),
  ('Creserh Consultoría Corporativa S. A. S. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.creserhcop.com', null, '33 1351 3198', 'Guadalajara, Jal.', 'curado', 'activo'),
  ('Human Services & Logistics Solutions S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://humanservices21.com', null, '33 3880 8900', 'Zapopan, Jal.', 'curado', 'activo'),
  ('Diaz Morones y Asociados, S. C.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.diazmorones.com.mx', null, '33 3630 3330', 'Guadalajara, Jal.', 'curado', 'activo'),
  ('Conexión Laboral de Occidente S. C.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.conexionlaboral.com.mx', null, '33 4170 8190', 'Guadalajara, Jalisco', 'curado', 'activo'),
  ('Azanza Soluciones Integrales S. C.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.grupoazanza.com', null, '33 3342 4040', 'Guadalajara, Jal.', 'curado', 'activo'),
  ('Servicios Connexus Mexico, S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'http://www.connexus.com.mx', null, '33 3070 0299', 'Guadalajara, Jal.', 'curado', 'activo'),
  ('Aurus Nivel Total S. de R. L. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://aurus.mx', null, '55 9056 4529', 'Naucálpan de Juárez, Estado de México', 'curado', 'activo'),
  ('Universidad de Monterrey (Centro de Desarrollo Profesional y Vinculación Laboral)', 'Institución / cámara empresarial — bolsa de empleo registrada ante STPS', 'https://www.udem.edu.mx', null, '81 8215 1000 EXT. 1190, 1191, 1525', 'Nuevo León', 'curado', 'activo'),
  ('Servicios Especializados en Recursos Humanos S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.seerh.com', null, '81 8123 4392/93/94', 'Nuevo León', 'curado', 'verificar'),
  ('HR Element S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'http://www.hrelement.mx', null, '81 4737 3939', 'Monterrey, N. L.', 'curado', 'activo'),
  ('Pro Multis S. C.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.promultisrh.com', null, '81 1297 9276', 'Apodaca, N. L.', 'curado', 'activo'),
  ('Tao RH S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://taorh.com.mx', null, '81 2039 4723', 'San Pedro Garza García, N. L.', 'curado', 'activo'),
  ('Compensación Aplicada S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.humanquality.com.mx', null, '81 8122 0000', 'Monterrey, Nuevo León', 'curado', 'activo'),
  ('Human Force RH S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.facebook.com/HUMANFO/', null, '81 8000 5734', 'San Pedro Garza García, N. L.', 'curado', 'activo'),
  ('Human Resource In Action, S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'http://www.humanresource.mx', null, '81 8020 8525', 'Monterrey, N. L.', 'curado', 'activo'),
  ('Operación y Distribución Monts S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://monts.mx', null, '22 2230 5501', 'San Andrés Cholula, Pue', 'curado', 'activo'),
  ('Procesos Betmun S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://procesosbetmun.com.mx', null, '22 2248 1870', 'Puebla, Pue.', 'curado', 'activo'),
  ('Cámara de la Industria Textil de Puebla y Tlaxcala S. A. de C. V.', 'Institución / cámara empresarial — bolsa de empleo registrada ante STPS', 'https://citexmexico.com', null, '222 243 4200 EXT. 105', 'Puebla, Pue', 'curado', 'activo'),
  ('Sips Especialistas en Recursos Humanos S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://sips.mx', null, '22 22 96 65 85; 222 644 22 84; CEL. 222 716 34 03', 'Puebla, Pue.', 'curado', 'activo'),
  ('Cdcmx-Centro de Capacitación Alemán S. de R. L. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://cdc-mexico.com', null, '22 2445 8426', 'Puebla, Pue.', 'curado', 'activo'),
  ('Universidad Politécnica de Querétaro', 'Institución / cámara empresarial — bolsa de empleo registrada ante STPS', 'https://upq.mx', null, '44 2101 9000', 'Querétaro', 'curado', 'activo'),
  ('Medina Consultores S. de R. L. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://medinaconsultores.mx', null, '44 2903 4157', 'Querétaro', 'curado', 'activo'),
  ('Agnes Soluciones Administrativas S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.reclutarh.com', null, '44 2244 9300', 'Querétaro, Qro.', 'curado', 'activo'),
  ('Saram HR S. de R. L. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://saram-hr.com', null, '84 4140 9550', 'Querétaro, Qro.', 'curado', 'activo'),
  ('Hca Desarrolladora de Talento Humano S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://hca-intelectualpeople.com', null, '44 2226 7340', 'Querétaro, Qro.', 'curado', 'activo'),
  ('Solución Integral de Administración de Personal S. de R. L. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://siap.com.mx', null, '42 7150 7369', 'Querétaro, Qro.', 'curado', 'activo'),
  ('Asesoría y Procesos Globales, S.A. de C.V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.facebook.com/APG.SA.DE.CV/', null, '44 4822 6361 EXT. 101', 'San Luis Potosí', 'curado', 'activo'),
  ('Cambio Organizacional, S. C.', 'Agencia de colocación privada — registrada ante STPS', 'https://cambioorganizacional.com.mx', null, '44 4174 6988', 'San Luis Potosí, S. L. P.', 'curado', 'activo'),
  ('Grupo Tonsuca S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://www.grupotonsuca.com', null, '44 4812 3405', 'San Luis Potosí, S. L. P.', 'curado', 'activo'),
  ('Shore HR Solutions Shrs S.C', 'Agencia de colocación privada — registrada ante STPS', 'https://www.shorehrs.com', null, '66 2210 6391', 'Hermosillo, Son.', 'curado', 'activo'),
  ('Gt RH en Soluciones Integrales S. de R. L. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://gtservice.mx', null, '68 6568 0507', 'Sonora', 'curado', 'verificar'),
  ('Branjo Soluciones Industriales S. de R. L. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://bsindustrial.com.mx', null, '89 9444 2089; 89 9444 2090', 'Reynosa, Tamaulipas', 'curado', 'verificar'),
  ('Mida Multiservicios Industriales S. de R. L. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://midamultiservicios.com', null, '89 9959 0056', 'Reynosa, Tams.', 'curado', 'verificar'),
  ('Leader People Servicios Administrativos S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'http://www.lpcorp.com.mx', null, '78 2826 8567', 'Poza Rica de Hidalgo, Ver.', 'curado', 'verificar'),
  ('Basset Soluciones S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://basset.com.mx', null, '99 9921 3415', 'Mérida, Yuc.', 'curado', 'activo'),
  ('Integración Corporativa del Mayab S. A. de C. V.', 'Agencia de colocación privada — registrada ante STPS', 'https://corporativomayab.com.mx', null, '99 9469 1910', 'Mérida, Yuc.', 'curado', 'activo'),
  ('Escala Negocios', 'Generalista CDMX', 'https://consultoriaparaempresa.com/', null, '8116782539', 'CDMX', 'curado', 'activo'),
  ('ISPROX', 'Generalista CDMX', 'https://isprox.com/', null, null, 'CDMX', 'curado', 'activo'),
  ('FORHUMAN', 'Generalista CDMX', 'https://forhuman.mx/', 'contacto@forhuman.mx', '5555013070', 'CDMX', 'curado', 'activo'),
  ('ALIATO', 'Generalista CDMX', 'https://www.aliato.mx/', 'contacto@aliato.mx', '55 5080 5800', 'CDMX', 'curado', 'activo'),
  ('OVERCAST', 'Generalista CDMX', 'https://overcastmx.com/', 'comercial@overcastmx.com', '55 8874 7400', 'CDMX', 'curado', 'activo'),
  ('TOTUM TALENT', 'Generalista MTY', 'https://totumtalent.com/', 'contacto@totumtalent.com', '8134408467', 'MTY', 'curado', 'activo');
