-- HRM NKUVO — seed de reclutadoras (regenerado 8 jul 2026 desde directorio_reclutadoras_hrm.xlsx)
-- 84 registros únicos (117 filas originales - 2 institucionales - 31 duplicados entre hojas)

alter table hrm_recruiters add column if not exists estado text default 'activo';

insert into hrm_recruiters (nombre, industria, sitio_web, email, telefono, ciudad, fuente, estado)
values
  ('Grupo CYH Corporativo', 'Generalista RH, Querétaro', null, null, '442 217 1979', 'Santiago de Querétaro, Qro.', 'curado', 'activo'),
  ('Evolucione Querétaro', 'Generalista RH, Querétaro', null, 'reclutamientoqueretaro@evolucione.net', '442 543 8975', 'Santiago de Querétaro, Qro.', 'curado', 'activo'),
  ('Operativo Evenplan', 'Generalista RH, Querétaro', 'https://www.evenplan.com.mx/', null, '442 224 0662', 'Santiago de Querétaro, Qro.', 'curado', 'activo'),
  ('Grupo Maas Recursos Humanos', 'Generalista RH, Querétaro', null, null, '442 215 1190', 'Santiago de Querétaro, Qro.', 'curado', 'activo'),
  ('Out Helping Corporativo', 'Generalista RH, Querétaro (oficina corporativa)', null, null, '442 215 9799', 'Santiago de Querétaro, Qro.', 'curado', 'activo'),
  ('Adecco Querétaro', 'Generalista, outsourcing/temporal, multinacional', 'https://www.adecco.com.mx/', 'calidadmx@adecco.com', '442 242 4425', 'Santiago de Querétaro, Qro. (San Ángel)', 'curado', 'activo'),
  ('Manpower Querétaro', 'Generalista, outsourcing/temporal, multinacional', 'https://www.manpower.com.mx/', null, '01 800 451 1400', 'Santiago de Querétaro, Qro. (Centro)', 'curado', 'activo'),
  ('Centro CIEE', 'Generalista RH, Querétaro', null, 'reclutamiento@centrociee.com.mx', '442 421 8046', 'Santiago de Querétaro, Qro. (Cimatario)', 'curado', 'activo'),
  ('Labor Mexicana', 'Generalista RH, Querétaro', null, null, '442 242 4989 / 477 763 1156', 'Santiago de Querétaro, Qro. (Alameda)', 'curado', 'activo'),
  ('Insourcing Professional Services', 'Generalista RH, Querétaro', null, 'aux.reclutamiento@ipsco.com.mx', '442 242 6463', 'Santiago de Querétaro, Qro. (Carretas)', 'curado', 'activo'),
  ('LMA Services', 'Generalista RH, Querétaro', null, null, '442 196 6110', 'Santiago de Querétaro, Qro. (Lomas de Casa Blanca)', 'curado', 'activo'),
  ('Worken', 'Generalista RH, Querétaro', null, null, '442 248 4952', 'Santiago de Querétaro, Qro. (se cambió de lugar, dirección no confirmada)', 'curado', 'verificar'),
  ('Brainware Assistance & Engineering', 'RH especializado en ingeniería', null, 'fernandonavarrete@brainware.com.mx', '442 212 4225', 'Santiago de Querétaro, Qro. (Alamos 2da Secc)', 'curado', 'activo'),
  ('OIRH', 'Generalista RH, Querétaro', null, 'marisol.flores@oirh.mx', '2950606', 'Santiago de Querétaro, Qro. (Milenio 3ra Secc)', 'curado', 'activo'),
  ('Velázquez', 'Generalista RH, Querétaro', 'velazques.com.mx', null, '442 226 4314', 'Santiago de Querétaro, Qro. (Centro Sur)', 'curado', 'activo'),
  ('Randstad Querétaro', 'Generalista, outsourcing/temporal, multinacional', 'https://www.randstad.mx/', null, '442 215 7665', 'Santiago de Querétaro, Qro. (El Marqués/Piamonte)', 'curado', 'activo'),
  ('CICESO Centro Integral de Evaluación', 'Evaluación psicométrica/assessment', null, 'lacayo@ciceso.com', '442 215 9618', 'Santiago de Querétaro, Qro. (Jardines de la Hacienda)', 'curado', 'activo'),
  ('Serpac Consulting', 'Generalista RH, Querétaro', null, 'serpac@serpac.net.mx', '442 242 3931', 'Santiago de Querétaro, Qro. (Mansiones del Valle)', 'curado', 'activo'),
  ('Out Helping (sucursal FINSA - Parque Industrial Querétaro)', 'Generalista RH, Querétaro', 'https://www.aet.mx', null, '442 215 9799', 'El Marqués, Qro. (Parque Industrial FINSA)', 'curado', 'activo'),
  ('Ecco México', 'Generalista RH, Querétaro', null, null, '442 220 7314', 'Santiago de Querétaro, Qro. (Parque Querétaro 2000)', 'curado', 'activo'),
  ('People Care', 'Generalista RH, Querétaro', null, 'eric.malo@peoplecare.com.mx', '442 213 8155', 'Santiago de Querétaro, Qro. (El Jacal)', 'curado', 'activo'),
  ('Lumi Sourcing', 'Generalista RH, Querétaro', null, 'nancyperez@lumipeople.com', '442 215 7695', 'Santiago de Querétaro, Qro. (Los Sauces)', 'curado', 'activo'),
  ('Soraa Consultores', 'Generalista RH, Querétaro', null, 'sofia.gonzales@soraaconsultores.com', '442 212 7171', 'Santiago de Querétaro, Qro. (Alamos 3ra Secc)', 'curado', 'activo'),
  ('TASI Soluciones en Capital Humano e IT', 'RH especializado en IT', null, 'octavio_ramirez@tasisoluciones.com', '442 388 1022', 'Santiago de Querétaro, Qro. (La Piedad)', 'curado', 'activo'),
  ('Sercah Consultores', 'Generalista RH, Querétaro', null, null, null, 'Santiago de Querétaro, Qro. (Residencial Italia, C.E.A.)', 'curado', 'verificar'),
  ('Recruitment & Human Solutions (RHS)', 'Generalista RH, Querétaro', 'https://www.rhs.com.mx/', 'paola.camarena@rhs.com.mx', '442 391 7888 / 442 561 7391', 'El Pueblito, Qro.', 'curado', 'activo'),
  ('A&F Estrategas', 'Generalista RH, Querétaro', null, null, '442 260 9090', 'Juriquilla, Qro. (Valle)', 'curado', 'verificar'),
  ('Out Helping (Centro de Reclutamiento, Parque Industrial Querétaro)', 'Generalista RH, Querétaro', null, null, '01 461 616 2712', 'Santiago de Querétaro, Qro. (Parque Industrial Querétaro)', 'curado', 'activo'),
  ('Narus Bolsa de Empleo', 'Bolsa de empleo/generalista, Querétaro', null, 'daniel.hernandez@narus.com.mx', '442 383 1424', 'Santiago de Querétaro, Qro. (Carretas)', 'curado', 'activo'),
  ('Team Solution México', 'Generalista RH, Querétaro', null, 'jmelo@teamrh.mx', '442 213 5323', 'Santiago de Querétaro, Qro. (Carretas)', 'curado', 'activo'),
  ('Out Helping (sucursal FINSA, El Marqués)', 'Generalista RH, Querétaro', null, null, '442 221 6500', 'El Marqués, Qro. (Parque Industrial FINSA)', 'curado', 'activo'),
  ('Out Helping (sucursal Marqués)', 'Generalista RH, Querétaro', null, null, '442 253 1123', 'El Marqués, Qro. (Parque Industrial El Marqués)', 'curado', 'activo'),
  ('Personae Consultores', 'Generalista RH, Querétaro', null, null, '442 161 2775', 'Santiago de Querétaro, Qro. (Fracc. Claustro del Sur)', 'curado', 'verificar'),
  ('Amrop / Seelinger y Conde', 'Multinacional, executive search C-level', 'https://www.amrop.com/mx/es/', null, '+52 81 2557 0417', 'Monterrey / CDMX', 'curado', 'activo'),
  ('ADECCO Nápoles', 'Generalista, outsourcing/temporal, multinacional', 'https://www.adecco.com.mx/', 'calidadmx@adecco.com', '800 832 9050 / 55 5062 5000', 'CDMX (Nápoles)', 'curado', 'activo'),
  ('AIRH Consultores', 'Generalista RH: reclutamiento, nómina, consultoría', 'https://www.airh.mx/', 'malmazan@airh.com.mx', '55 6017 7670', 'CDMX (Del Valle)', 'curado', 'activo'),
  ('Al Smith y Asociados', 'Ejecutivo/boutique, investigación directa', 'http://alsmith.com.mx/', 'alsmith@alsmith.com.mx', null, 'Querétaro', 'curado', 'activo'),
  ('Alpe Consultores', 'Consultoría gerencial/capacitación', 'http://www.alpeconsultores.com.mx/', null, '55 5524 1720 / 55 5362 9147', 'CDMX (Del Valle)', 'curado', 'verificar'),
  ('Antal International', 'Multinacional generalista (IT/ingeniería/ventas)', 'https://www.antal.com/recruitment/mexico-p', null, null, 'CDMX (Polanco)', 'curado', 'activo'),
  ('APOYO CONFIABLE DE PERSONAL', 'Generalista ejecutivo/operativo', 'https://www.apoyoconfiabledepersonal.com.mx/', 'apoyoconfiable@prodigy.net.mx', '55 5744 4500', 'CDMX (Roma Norte)', 'curado', 'activo'),
  ('ARGÜELLES CAPITAL EJECUTIVO', 'Boutique ejecutivo, +30 años', 'https://www.capitalejecutivo.com.mx/', 'arguelles@capitalejecutivo.com.mx', '55 1085 7233 / 55 5662 3858', 'CDMX (Santa Fe)', 'curado', 'activo'),
  ('ARMSTRONG', 'Evaluación psicométrica / plataforma tecnológica', 'https://www.armstrong.com.mx/', 'comunidad@armstrong.com.mx', '55 5212 1020', 'CDMX', 'curado', 'activo'),
  ('ASIRH', 'Generalista RH, outsourcing/nómina', 'http://www.asirh.com.mx/', 'direccion.general@asirh.com.mx', '+52 222 248 0959', 'Puebla', 'curado', 'activo'),
  ('AVANTGARDE (AGHCC)', 'Executive search + team building + assessment', 'https://www.aghcc.com/', 'contacto@aghcc.com', '+52 55 3640 0552', 'CDMX / Monterrey / Querétaro', 'curado', 'activo'),
  ('AXIS CONSULTORES', 'Generalista RH: headhunting + nómina', 'https://axisconsultores.com/', 'ventas@axisconsultores.com', '55 5559 3833 / 3839', 'CDMX (Del Valle)', 'curado', 'activo'),
  ('Aymerich Business & Consulting', 'Boutique especializado Telecom/IT/Ingeniería', 'https://aymerichbc.com/', 'corporativo@aymerichbc.com', '55 5017 5662 / 55 2628 0627', 'Edo. México (Tlalnepantla/Ecatepec)', 'curado', 'activo'),
  ('BARREDA CONSULTORES', 'Boutique ejecutivo alto/medio, red internacional', 'https://barredaygonzalez.com/', null, null, 'CDMX (Del Valle)', 'curado', 'activo'),
  ('BE EXECUTIVE', 'Reclutamiento ejecutivo + estudios socioeconómicos', 'http://www.beexecutive.com/', null, null, 'CDMX (sin confirmar)', 'curado', 'verificar'),
  ('BEST RECURSOS HUMANOS', 'Generalista + outsourcing/nómina, 25+ años', 'https://bestrecursoshumanos.com', 'reclutamiento@bestrecursoshumanos.com', '+52 55 5661 3336', 'CDMX (Guadalupe Inn)', 'curado', 'activo'),
  ('BLEUMIND', 'Boutique ejecutivo + career transition', 'https://bleumind.com', 'contacto@bleumind.com', 'no publicado (WhatsApp/LinkedIn)', 'San Pedro Garza García, N.L.', 'curado', 'activo'),
  ('Boege & Business', 'Boutique germano-mexicana, RH para empresas europeas', 'https://boege-b.com.mx', 'info@boege-b.com.mx', '+52 55 5953 3083', 'CDMX (Santa Fe)', 'curado', 'activo'),
  ('Boyden Mexico', 'Multinacional, ejecutivo/C-level y board', 'https://boyden.com/mexico/', 'mexico@boyden.com', '+52 55 3145 9263', 'CDMX (Santa Fe)', 'curado', 'activo'),
  ('C&H Empresarial', 'Outsourcing/suministro de personal', 'https://cyhempresarial.com', 'gerente.celaya@cyhempresarial.com.mx', '461 159 5576', 'Celaya, Guanajuato', 'curado', 'verificar'),
  ('CASE CONSULTORES', 'Generalista, búsqueda y selección de talento', 'https://caseconsultores.com.mx', null, '+52 55 5663 2400', 'CDMX (Insurgentes)', 'curado', 'activo'),
  ('CATENON', 'Multinacional tech-driven executive search', 'https://catenon.com', null, null, 'Internacional (HQ Madrid)', 'curado', 'activo'),
  ('CLAUDIO BENITEZ CONSULTORES', 'Selección de directivos y gerentes', 'http://www.claudiobenitezheadhunter.com/', null, '222 357 0534', 'Puebla / Edo. México (fuentes distintas)', 'curado', 'verificar'),
  ('COCA CONSULTORES', 'Generalista RH + fiscal/contable, 25+ años', 'https://cocaconsultores.com', 'contacto@cocaconsultores.com', '(55) 2454 2174 / 2175', 'CDMX (Álvaro Obregón)', 'curado', 'activo'),
  ('Confisa Group', 'Boutique internacional retained executive search', 'https://confisagroup.com', 'info@confisagroup.com', '+52 55 1660 8135', 'CDMX (Polanco)', 'curado', 'activo'),
  ('Consystar Consultores', 'Generalista: RH, reclutamiento, head hunting', 'https://consystar.mx', 'marta.rodriguez@consystar.com', '55 5611 4553 / 6910', 'CDMX (Álvaro Obregón)', 'curado', 'activo'),
  ('COSMIC', 'Outsourcing/staffing de alto volumen', 'https://cosmic.com.mx', 'info@grupocosmic.com', '800 288 9353', 'CDMX (Benito Juárez)', 'curado', 'activo'),
  ('CREO SERVICES', 'Ejecutivo/generalista, 12+ años', 'https://creoservices.com', 'direccion@creoservices.com', '+52 81 8335 0492', 'Monterrey / San Pedro Garza García', 'curado', 'activo'),
  ('Cuadrivium', 'Outsourcing/administración de RH, desde 1999', 'https://cuadrivium.com', null, null, 'CDMX (Guadalupe Inn)', 'curado', 'activo'),
  ('DEZA SEARCH', 'Boutique ejecutivo multinacional, desde 1990', 'https://dezasearch.com', 'contacto@dezasearch.com', '+52 55 5241 5221', 'CDMX (Río Lerma)', 'curado', 'activo'),
  ('DHR Global (antes DHR International)', 'Multinacional top-5 global retained search, C-level', 'https://dhrglobal.com', null, '+52 55 5281 4849', 'CDMX (Reforma)', 'curado', 'activo'),
  ('DIRECCION HUMANA', 'Generalista: reclutamiento, estudios socioeconómicos', 'https://direccionhumana.com', 'info@direccionhumana.com', '(55) 2848 6393 / 2724 1970', 'CDMX (Polanco)', 'curado', 'activo'),
  ('Dúo Sinergia', 'Outsourcing/nómina + generalista, multi-sucursal', 'https://duosinergia.com', 'hermosillo@duosinergia.com', '(55) 5543 0205', 'CDMX / Guadalajara / Hermosillo', 'curado', 'activo'),
  ('E People Consulting', 'RH generalista (reclutamiento, capacitación, coaching)', 'https://epeopleconsulting.com', 'clientes@epeopleconsulting.org', null, 'San Pedro Garza García, N.L.', 'curado', 'activo'),
  ('EGON ZEHNDER INTERNACIONAL', 'Multinacional boutique, executive/board search C-level', 'https://www.egonzehnder.com', null, '55 5540 7635', 'CDMX (Lomas de Chapultepec)', 'curado', 'activo'),
  ('Ejecutivos Seleccionados (GES)', 'Generalista Head Hunting + planta + payrolling, desde 1971', 'https://www.grupoejecutivos.com', null, '55 5523 5731', 'CDMX (Del Valle)', 'curado', 'activo'),
  ('EliteBrain.com', 'Multinacional boutique, C-level + coaching (Grupo Confisa Intl.)', 'https://elitebrain.com', 'info@elitebrain.com', null, 'CDMX (Polanco) / Monterrey', 'curado', 'activo'),
  ('EULEN', 'Multinacional outsourcing/facility services', 'https://www.eulen.com.mx', null, '(55) 5002 7000', 'CDMX (Del Valle)', 'curado', 'activo'),
  ('EXCELENCIA', 'RH generalista, reclutamiento y selección', 'https://excelencia.com.mx', null, '(55) 9418 7236', 'CDMX (Polanco)', 'curado', 'activo'),
  ('Global Recruiters', 'Boutique internacional, manufactura/hospitalidad', 'https://global-recruiters.com', 'info@global-recruiters.com', '+52 664 881 0378 (WhatsApp)', 'Tijuana, Baja California', 'curado', 'activo'),
  ('Great Team Empresarial', 'RH generalista para PyMEs', 'https://greatteam.mx', 'ventas@greatteam.com.mx', '55 2489 0216 / 0217', 'CDMX (Roma Norte)', 'curado', 'activo'),
  ('Grupo Argos / StarChoice', 'Headhunting supervisión/gerencial/directivo, foco turismo', 'https://www.starchoice.com.mx', 'info@starchoice.com.mx', '998 241 4622', 'Cancún, Quintana Roo', 'curado', 'activo'),
  ('Grupo DCH', 'Reclutamiento ejecutivo/operativo/masivo + REPSE', 'https://dchkw.com.mx', 'contacto@dchkw.com.mx', '55 5393 1490 / 55 6350 9982', 'Naucalpan, Edo. México', 'curado', 'activo'),
  ('Korn Ferry México', 'Multinacional, executive search + consultoría organizacional', 'https://www.kornferry.com/', null, '55 5095 9500', 'CDMX (Lomas de Chapultepec) / Monterrey', 'curado', 'activo'),
  ('Michael Page / PageGroup México', 'Multinacional, selección especializada y ejecutiva', 'https://www.michaelpage.com.mx/', null, null, 'CDMX (Reforma) / Monterrey / Guadalajara', 'curado', 'activo'),
  ('T-mapp', 'Reclutamiento tech-enabled con IA', 'https://t-mapp.com/', null, null, 'Origen Colombia, opera en México sin oficina confirmada', 'curado', 'verificar'),
  ('Hireline', 'Reclutamiento de talento tecnológico (TI) con IA', 'https://hireline.io/', 'contacto@hireline.io', null, 'Querétaro', 'curado', 'verificar'),
  ('Lupa Hire', 'Staffing/EOR/RPO remoto, roles tech y senior', 'https://lupahire.com/', 'talent@lupahire.com', null, 'Remoto LatAm (México, Colombia, Argentina, Brasil)', 'curado', 'verificar'),
  ('Top Hire', 'Executive search para multinacionales y Fortune 500', 'https://top-hire.com/', null, null, 'México (sin confirmar)', 'curado', 'verificar'),
  ('People Connect / People Connection', 'RH integral: reclutamiento, nómina, psicometrías', 'https://peopleconnect.com.mx/', 'recursoshumanos@peopleconnect.com.mx', '(55) 6820 3100 CDMX / (222) 934 5100 Puebla', 'CDMX / Puebla / Toluca', 'curado', 'verificar'),
  ('ALGI Consultores', 'Reclutamiento consultivo, psicometrías, capacitación, RH integral', 'https://algi.mx/', 'hola@algi.mx', '+52 55 7100 0200 / 55 6297 1084', 'CDMX / Puebla / Querétaro / Tlaxcala / Morelos', 'curado', 'activo');